### ISSUE TITLE
Crashes server 1.18.2

### ISSUE THREAD

**Issue by DTX3** [dima-dencep/blur-forge#1]
Upon starting my server, it crashes with the following error: 

Mod File: /C:/Users/DTX3/Desktop/Minecraft Server/mods/blur-2.4.2+mc1.18.2-build.3.jar
	Failure message: Blur (Forge) (blur) has failed to load correctly
		java.lang.reflect.InvocationTargetException: null
	Mod Version: 2.4.2+mc1.18.2-build.3
	Mod Issue URL: https://github.com/dimadencep/Blur-Forge/issues
	Exception message: java.lang.ClassNotFoundException: net.minecraft.client.gui.screens.ChatScreen

Stacktrace:
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:138) ~[securejarhandler-1.0.3.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?] {}
	at com.tterrag.blur.Blur.<init>(Blur.java:42) ~[blur-2.4.2+mc1.18.2-build.3.jar%2368!/:2.4.2+mc1.18.2-build.3] {re:classloading}
	at jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:483) ~[?:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:67) ~[javafmllanguage-1.18.2-40.2.0.jar%23212!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:106) ~[fmlcore-1.18.2-40.2.0.jar%23211!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

**Comment by dima-dencep** [comment]
This is a client-side mod...

**Comment by DTX3** [comment]
Ah ok. Although removing it from the server and having client side only, also crashes. I'll create a separate issue for it.
